# -*- coding: utf-8 -*-
"""ranking-based-on-relevancy-score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z4eLklXKd67-OOv4KbltqF4CGOuAJRAx
"""

import pandas as pd
import ast

# Load the CSV file
df = pd.read_csv('.../relevancy_with_scores.csv')

# Function to extract and concatenate top-n sentences from the ranked context
def extract_top_n(ranked_context, n):
    try:
        # Convert the string representation of list to an actual list
        context_list = ast.literal_eval(ranked_context)
        # Join the first n sentences
        top_n_sentences = ' '.join(context_list[:n])
        return top_n_sentences
    except:
        return ''

# Apply the function to the ranked context column and create new columns for top-1 to top-5
for n in range(1, 6):
    column_name = f'top{n}'
    df[column_name] = df['ranked context'].apply(lambda x: extract_top_n(x, n))

# Save the modified dataframe to a new CSV file
df.to_csv('dataset-topn-updated.csv', index=False)

print("Top-1 to top-5 sentences have been extracted.")